# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fanova_cpp <- function(data, matrix_clusters) {
    .Call('_HDSpatialScan_fanova_cpp', PACKAGE = 'HDSpatialScan', data, matrix_clusters)
}

fmanova_cpp <- function(jeu, matrice_clusters, cst1, cst2) {
    .Call('_HDSpatialScan_fmanova_cpp', PACKAGE = 'HDSpatialScan', jeu, matrice_clusters, cst1, cst2)
}

pointwise_mtest_cpp <- function(data_transp, matrix_clusters) {
    .Call('_HDSpatialScan_pointwise_mtest_cpp', PACKAGE = 'HDSpatialScan', data_transp, matrix_clusters)
}

